layout_spectrum: 1
typography_spectrum: 0.123946
color:
  lightness: 0.5092749
  brandStrength: 0.7913658
  saturation: 0.2977242
  rhythmicContrast: 0.327563
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Tropical Dreams Troncones
